export const BASE_URL = "http://stage.services.machineshop.io/api/v1";
//export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const GET_BUTTON_LIST = "GET_BUTTON_LIST";
export const GET_BUTTON_LIST_SUCCESS = "GET_BUTTON_LIST_SUCCESS";
export const GET_BUTTON_LIST_FAILURE = "GET_BUTTON_LIST_FAILURE";

export const SAVE_CREDENTIALS = "SAVE_CREDENTIALS";

export const REQUEST_INTEGRATIONS = "REQUEST_INTEGRATIONS";
export const REQUEST_INTEGRATIONS_FAILURE = "REQUEST_INTEGRATIONS_FAILURE";
export const REQUEST_INTEGRATIONS_SUCCESS = "REQUEST_INTEGRATIONS_SUCCESS";

export const REQUEST_CONFIGURE_BUTTON = "REQUEST_CONFIGURE_BUTTON";
export const REQUEST_CONFIGURE_BUTTON_FAILURE = "REQUEST_CONFIGURE_BUTTON_FAILURE";
export const REQUEST_CONFIGURE_BUTTON_SUCCESS = "REQUEST_CONFIGURE_BUTTON_SUCCESS";

export const REQUEST_PROVISIONING = "REQUEST_PROVISIONING";
export const REQUEST_PROVISIONING_FAILURE = "REQUEST_PROVISIONING_FAILURE";
export const REQUEST_PROVISIONING_SUCCESS = "REQUEST_PROVISIONING_SUCCESS";

export const SET_CURRENT_BUTTON = "SET_CURRENT_BUTTON";
export const SET_CURRENT_BUTTON_FAILURE = "SET_CURRENT_BUTTON_FAILURE";
export const SET_CURRENT_BUTTON_SUCCESS = "SET_CURRENT_BUTTON_SUCCESS";

//export const REQUEST_SAVE_LOGIN_CREDENTIALS = "REQUEST_SAVE_LOGIN_CREDENTIALS";
export const SAVE_LOGIN_CREDENTIALS_SUCCESS = "SAVE_LOGIN_CREDENTIALS_SUCCESS";
//export const SAVE_LOGIN_CREDENTIALS_FAILURE = "SAVE_LOGIN_CREDENTIALS_FAILURE";

export const REQUEST_SAVE_WIFI_CREDENTIALS = "REQUEST_SAVE_WIFI_CREDENTIALS";
export const SAVE_WIFI_CREDENTIALS_SUCCESS = "SAVE_WIFI_CREDENTIALS_SUCCESS";
export const SAVE_WIFI_CREDENTIALS_FAILURE = "SAVE_WIFI_CREDENTIALS_FAILURE";
